language: node_js
node_js:
- "node"

dist: bionic
sudo: false

addons:
  ssh_known_hosts:
    - 45.79.215.5

    before_install:
- openssl aes-256-cbc -K $encrypted_92374bf4733f_key -iv $encrypted_92374bf4733f_iv
  -in scripts/gridsome-deploy.enc -out scripts/gridsome-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/gridsome-deploy ~/.ssh/gridsome-deploy
- chmod 600 ~/.ssh/gridsome-deploy
- ssh-add ~/.ssh/gridsome-deploy
- echo -e "Host 192.0.2.2\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master