#!/bin/bash
set -x

gridsome build

# Configure Git to only push the current branch
git config --global push.default simple

# Remove .gitignore and replace with the production version
rm -f .gitignore
cp scripts/prodignore .gitignore
cat .gitignore

# Add the Linode production server as a remote repository
git remote add production ssh://andrew@45.79.215.5:/home/andrew/gridsomebare.git

# Add and commit all the static files generated by the Gridsome build
git add . && git commit -m "Gridsome build"

# Push all changes to the Linode production server
git push -f production HEAD:refs/heads/master
